---
- hosts: wtl
  become: yes
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: apt-get -y install python-simplejson
  roles:
    - packages
    - ssh
    - nginx
    - weechat
    - ufw
