- name: Add weechat repo key
  apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: 11E9DE8848F2B65222AA75B8D1820DB22A11534E

- apt_repository:
    repo: deb https://weechat.org/ubuntu xenial main
    state: present

- name: Add repositories
  with_items:
    - ppa:brightbox/ruby-ng
    - ppa:certbot/certbot
    - ppa:neovim-ppa/stable
  apt_repository: repo={{ item }}

- name: Install packages
  become: true
  apt: name={{ item }} state=present update_cache=true
  with_items:
    - unattended-upgrades
    - fail2ban
    - ufw
    - openssh-server
    - git
    - nginx
    - software-properties-common
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    - python-certbot-nginx
    - weechat-plugins
    - weechat-curses
    - weechat
    - mosh
    - screen
    - neovim
