- name: Add weechat repo key
  apt_key:
    keyserver: keys.gnupg.net
    id: 11E9DE8848F2B65222AA75B8D1820DB22A11534E

- apt_repository:
    repo: deb https://weechat.org/ubuntu artful main
    state: present

- name: Add repositories
  with_items:
    - ppa:brightbox/ruby-ng
    - ppa:certbot/certbot
  apt_repository: repo={{ item }}

- name: Install packages
  become: true
  apt: name={{ item }} state=present update_cache=true
  with_items:
    - openssh-server
    - git
    - nginx
    - software-properties-common
    - python-certbot-nginx
    - weechat
    - mosh
