---
- name: copy nginx site file
  template: src=default.j2 dest=/etc/nginx/sites-available/default

# - name: Copy nginx configuration
#   template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: install setfacl support
  become: yes
  apt: pkg=acl

- name: Create dir for index.html
  file: path=/www/ state=directory

- name: Copy index.html
  copy: src=files/index.html dest=/www/index.html
